export enum ApiCodeResponse {
  TEST = 'api.result.test',
  NO_TOKEN_FOUND = 'api.security.no_token_found',
  USER_NOT_FOUND = 'api.security.user_not_found',
  TOKEN_EXPIRED = 'api.security.token_expired',
  SIGNUP_EXCEPTION = 'api.security.signup_exception',
  CREDENTIAL_DELETED = 'api.security.credential_deleted',
  USER_ALREADY_EXISTS = 'api.security.user_already_exists',
  TOKEN_GEN_EXCEPTION = 'api.security.token_gen_exception',
  UNAUTHORIZED = 'api.result.unauthorized',
  SUCCESS = 'api.result.success',
  ACCOUNT_CREATED = 'api.account.created',
  ACCOUNT_UPDATED = 'api.account.updated',
  ACCOUNT_DELETED = 'api.account.deleted',
  PAYLOAD_IS_NOT_VALID = 'api.result.payload.is_not_valid',
  PAYLOAD_PARAM_IS_MISSING = 'api.result.payload_param_is_missing',
  USERNAME_LENGTH = 'api.error.username_length',
  USERNAME_EMPTY = 'api.error.username_is_missing',
  PASSWORD_LENGTH = 'api.error.password_length',
  PASSWORD_EMPTY = 'api.error.password_is_missing',
  MAIL_EMAIL = 'api.error.mail_invalid',
  MAIL_EMPTY = 'api.error.mail_empty',
  COMMON_SUCCESS = 'api.success.common',
}
